# .github/workflows/daily-pages.yml
name: Create Daily SEO Pages

on:
  schedule:
    # Runs at 9 AM UTC every day
    - cron: '0 9 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  create-pages:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create 5 new pages
      env:
        SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
        SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
        SANITY_API_WRITE_TOKEN: ${{ secrets.SANITY_API_WRITE_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        node scripts/create-daily-pages.js
        
    - name: Update sitemap
      run: |
        node scripts/update-sitemap.js
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/sitemap.xml
        git diff --quiet && git diff --staged --quiet || git commit -m "Update sitemap with new pages"
        git push
